extract = 'Time elapsed: (\d+) us'
benchmarks = 'test/**/*.btor2'

[runs.baseline]
pipeline = [
    "target/release/btor2i -f {file_path} {args}",
]

[runs.myopt] 
pipeline = [
    "target/release/btor2i -f {file_path} {args}",
]
